/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/text": {
    get: operations["AppController_text"];
  };
  "/json": {
    get: operations["AppController_json"];
  };
  "/xml": {
    get: operations["AppController_xml"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorDto: {
      statusCode: number;
      message: string;
    };
    ServerErrorDto: {
      statusCode: number;
      message: string;
    };
    JsonDto: {
      data: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AppController_text: {
    responses: {
      200: {
        content: {
          "text/plain": string;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      "5XX": {
        content: {
          "application/json": components["schemas"]["ServerErrorDto"];
        };
      };
    };
  };
  AppController_json: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JsonDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      "5XX": {
        content: {
          "application/json": components["schemas"]["ServerErrorDto"];
        };
      };
    };
  };
  AppController_xml: {
    responses: {
      200: {
        content: {
          "application/xml": string;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      "5XX": {
        content: {
          "application/json": components["schemas"]["ServerErrorDto"];
        };
      };
    };
  };
}
